import streamlit as st
import pandas as pd
import sqlite3
import plotly.graph_objects as go
import plotly.express as px
from datetime import datetime, date
import io
import warnings
import os

warnings.filterwarnings("ignore")

EXCEL_FOLDER = "Excel files"
DATABASE_FOLDER = "Database"
RESULTS_FOLDER  = "Results"

st.set_page_config(
    page_title="Pub Forecast",
    page_icon="🍺",
    layout="wide"
)

# Session state — persists across tabs and reruns

if "dark_mode" not in st.session_state:
    st.session_state.dark_mode = False

if "selected_pub" not in st.session_state:
    st.session_state.selected_pub = "local"  # default to local pub

# Per-pub config — db files, display names, forecast file prefixes
PUB_OPTIONS = {
    "local": {
        "label":       "🏠  Local Pub",
        "db_file":     "pub_sales.db",
        "prefix":      "",
        "peak_days":   "Thursday & Friday",
        "peak_season": "Christmas (December)",
    },
    "riverside": {
        "label":       "🌊  Riverside Pub (London)",
        "db_file":     "riverside_pub_sales.db",
        "prefix":      "riverside_",
        "peak_days":   "Thursday – Sunday",
        "peak_season": "Summer (June – August)",
    },
}

active_pub = PUB_OPTIONS[st.session_state.selected_pub]

dark = st.session_state.dark_mode

if dark:
    BG        = "#111827"
    CARD_BG   = "#1f2937"
    CARD_BDR  = "#374151"
    TEXT_MAIN = "#f9fafb"
    TEXT_SUB  = "#9ca3af"
    SIDEBAR   = "#1f2937"
    PLOT_BG   = "#1f2937"
    GRID_CLR  = "#374151"
else:
    BG        = "#ffffff"
    CARD_BG   = "#f9fafb"
    CARD_BDR  = "#e5e7eb"
    TEXT_MAIN = "#111827"
    TEXT_SUB  = "#6b7280"
    SIDEBAR   = "#f3f4f6"
    PLOT_BG   = "#ffffff"
    GRID_CLR  = "#f0f0f0"

st.markdown(f"""
<style>
    html, body, [data-testid="stAppViewContainer"], [data-testid="stMain"] {{
        background-color: {BG} !important;
        color: {TEXT_MAIN} !important;
    }}
    [data-testid="stSidebar"] {{
        background-color: {SIDEBAR} !important;
    }}
    [data-testid="stSidebar"] * {{ color: {TEXT_MAIN} !important; }}
    .metric-card {{
        background-color: {CARD_BG};
        border: 1px solid {CARD_BDR};
        border-radius: 10px;
        padding: 20px 16px;
        text-align: center;
    }}
    .metric-value {{
        font-size: 26px;
        font-weight: 700;
        color: {TEXT_MAIN};
    }}
    .metric-label {{
        font-size: 12px;
        color: {TEXT_SUB};
        margin-top: 6px;
    }}
    .alert-high {{
        background-color: #fef2f2;
        border-left: 5px solid #dc2626;
        padding: 12px 16px; border-radius: 6px;
        margin: 5px 0; color: #7f1d1d; font-size: 14px;
    }}
    .alert-med {{
        background-color: #fffbeb;
        border-left: 5px solid #d97706;
        padding: 12px 16px; border-radius: 6px;
        margin: 5px 0; color: #78350f; font-size: 14px;
    }}
    .alert-ok {{
        background-color: #f0fdf4;
        border-left: 5px solid #16a34a;
        padding: 12px 16px; border-radius: 6px;
        margin: 5px 0; color: #14532d; font-size: 14px;
    }}
    h1, h2, h3 {{ color: {TEXT_MAIN} !important; }}
    p, span, div {{ color: {TEXT_MAIN}; }}
    .stDataFrame {{ background-color: {CARD_BG}; }}
    [data-testid="stTabs"] [role="tab"] {{
        font-size: 15px;
        font-weight: 600;
        padding: 10px 24px;
    }}
</style>
""", unsafe_allow_html=True)


# Data loading functions — cached per pub_key so switching pub triggers a reload

@st.cache_data
def load_historical(pub_key):
    db_file = PUB_OPTIONS[pub_key]["db_file"]
    conn = sqlite3.connect(os.path.join(DATABASE_FOLDER, db_file)) # retrieve data from correct database
    daily_sales = pd.read_sql("SELECT * FROM daily_sales", conn)
    conn.close()
    daily_sales["date"] = pd.to_datetime(daily_sales["date"])
    return daily_sales.sort_values("date").reset_index(drop=True)

@st.cache_data
def load_metrics(pub_key):
    prefix = PUB_OPTIONS[pub_key]["prefix"]
    try:
        return pd.read_csv(os.path.join(EXCEL_FOLDER, f"{prefix}forecast_model_comparison.csv"))
    # generated by evaluate.py
    except Exception:
        return pd.DataFrame({  # fallback if file missing
            "Model":    ["Random Forest (200 trees)", "Decision Tree (max_depth=5)",
                         "SARIMAX (1,1,1)x(0,1,1,7)", "Exponential Smoothing",
                         "SARIMA (1,1,1)x(0,1,1,7)", "Moving Average (7-day)",
                         "Linear Regression"],
            "MAPE (%)": [13.72, 18.64, 20.13, 24.08, 24.54, 131.14, 35.00],
            "RMSE (£)": [2559,  3825,  2501,  4116,  4053,  8264,   5200]
        })

@st.cache_data
def build_ml_models(pub_key):
    from sklearn.tree import DecisionTreeRegressor
    from sklearn.ensemble import RandomForestRegressor

    db_file = PUB_OPTIONS[pub_key]["db_file"]
    seed    = 42 if pub_key == "local" else 99

    conn = sqlite3.connect(os.path.join(DATABASE_FOLDER, db_file)) # retrieve data from correct database
    daily_sales = pd.read_sql("SELECT * FROM daily_sales", conn)
    conn.close()

    daily_sales["date"] = pd.to_datetime(daily_sales["date"])
    daily_sales = daily_sales.sort_values("date").reset_index(drop=True)

    full_dates  = pd.date_range(start=daily_sales["date"].min(),
                                end=daily_sales["date"].max(), freq="D")
    daily_sales = daily_sales.set_index("date").reindex(full_dates)
    daily_sales.index.name   = "date"
    daily_sales["weekday"]   = daily_sales.index.day_name()
    daily_sales["weather"]   = daily_sales["weather"].fillna("Cloudy")
    daily_sales["sales_gbp"] = daily_sales["sales_gbp"].ffill()
    daily_sales = daily_sales.reset_index()

    # event dates and seasonal feature differ per pub
    if pub_key == "local":
        event_dates  = ["2025-01-01","2025-10-31","2025-12-24","2025-12-25","2025-12-26"]
        extra_feat   = "is_december"
        extra_col    = (daily_sales["date"].dt.month == 12).astype(int)  # local pub peaks in December
    else:
        event_dates  = ["2025-01-01","2025-02-14","2025-04-18","2025-04-20",
                        "2025-05-05","2025-08-25","2025-10-31",
                        "2025-12-24","2025-12-25","2025-12-26","2025-12-31"]
        extra_feat   = "is_summer"
        extra_col    = daily_sales["date"].dt.month.isin([6, 7, 8]).astype(int)  # riverside peaks in summer

    daily_sales["is_event"]    = daily_sales["date"].astype(str).isin(event_dates).astype(float) * 0.5  # boost sales for events
    daily_sales["is_rainy"]    = (daily_sales["weather"] == "Rainy").astype(int)
    daily_sales["is_sunny"]    = (daily_sales["weather"] == "Sunny").astype(int)
    daily_sales["is_cold"]     = (daily_sales["weather"] == "Cold").astype(int)
    daily_sales["lag_1"]       = daily_sales["sales_gbp"].shift(1)   # yesterday's sales
    daily_sales["lag_7"]       = daily_sales["sales_gbp"].shift(7)   # sales from last week
    daily_sales["lag_14"]      = daily_sales["sales_gbp"].shift(14)  # sales from 2 weeks ago
    daily_sales["roll_7_mean"] = daily_sales["sales_gbp"].shift(1).rolling(7).mean()  # average sales over last 7 days
    daily_sales["roll_7_std"]  = daily_sales["sales_gbp"].shift(1).rolling(7).std()   # how much sales varied last week
    daily_sales["day_of_week"] = daily_sales["date"].dt.dayofweek
    daily_sales["month_num"]   = daily_sales["date"].dt.month
    daily_sales[extra_feat]    = extra_col

    ml_feature_cols = ["lag_1","lag_7","lag_14","roll_7_mean","roll_7_std",
                       "day_of_week","month_num", extra_feat,
                       "is_event","is_rainy","is_sunny","is_cold"]

    daily_sales = daily_sales.dropna(subset=ml_feature_cols).reset_index(drop=True)
    split   = int(len(daily_sales) * 0.8)
    X_train = daily_sales.iloc[:split][ml_feature_cols]
    y_train = daily_sales.iloc[:split]["sales_gbp"]

    dt = DecisionTreeRegressor(max_depth=5, min_samples_leaf=5, random_state=seed)
    dt.fit(X_train, y_train)

    rf = RandomForestRegressor(n_estimators=200, max_depth=8,
                               min_samples_leaf=3, random_state=seed, n_jobs=-1)  # use all CPU cores
    rf.fit(X_train, y_train)

    fi_df = pd.DataFrame({
        "Feature":    ml_feature_cols,
        "Importance": rf.feature_importances_
    }).sort_values("Importance", ascending=False).reset_index(drop=True)

    return dt, rf, fi_df, ml_feature_cols

@st.cache_data
def load_forecast(pub_key):
    prefix = PUB_OPTIONS[pub_key]["prefix"]
    daily_sales = pd.read_excel(os.path.join(EXCEL_FOLDER, f"{prefix}forecast_2026.xlsx"))
    daily_sales["date"] = pd.to_datetime(daily_sales["date"])
    daily_sales["weekday"] = daily_sales["date"].dt.day_name()

    keep_cols = ["date", "weekday", "forecast_sales_gbp"]
    for col in ["weather", "is_rainy", "is_sunny", "is_cold"]:
        if col in daily_sales.columns:
            keep_cols.append(col)

    return daily_sales[keep_cols]

@st.cache_data
def load_scenarios(pub_key):
    prefix = PUB_OPTIONS[pub_key]["prefix"]
    try:
        daily_sales = pd.read_excel(os.path.join(EXCEL_FOLDER, f"{prefix}forecast_2026_scenarios.xlsx"))  # all 3 scenarios
        daily_sales["date"] = pd.to_datetime(daily_sales["date"])
        return daily_sales
    except Exception:
        return None


# Load all data — keyed by selected_pub so switching pub reloads everything

pub_key = st.session_state.selected_pub


try:
    hist_df     = load_historical(pub_key)
    metrics_df  = load_metrics(pub_key)
    forecast_df = load_forecast(pub_key)
    scenario_df = load_scenarios(pub_key)

    best_mape_row = metrics_df.loc[metrics_df["MAPE (%)"].idxmin()]
    best_rmse_row = metrics_df.loc[metrics_df["RMSE (£)"].idxmin()]

    sarimax_rows = metrics_df[metrics_df["Model"].str.startswith("SARIMAX", na=False)]
    production_row = sarimax_rows.iloc[0] if not sarimax_rows.empty else metrics_df.iloc[0]

    with st.spinner("Building models (first load only — cached after)..."):
        dt_model, rf_model, fi_df, ml_feature_cols = build_ml_models(pub_key)

except Exception as e:
    st.error(f"Error loading data: {e}")
    st.stop()


# Weather display config

WEATHER_ICON = {"Sunny": "☀️", "Cloudy": "☁️", "Rainy": "🌧️", "Cold": "🥶"}

WEATHER_GRADIENT = {
    "Sunny":  "linear-gradient(135deg,#f59e0b,#fbbf24)",
    "Cloudy": "linear-gradient(135deg,#6b7280,#9ca3af)",
    "Rainy":  "linear-gradient(135deg,#1d4ed8,#3b82f6)",
    "Cold":   "linear-gradient(135deg,#0369a1,#38bdf8)",
}

WEATHER_NOTES = {
    "Rainy":  "⚠️ Rain forecast — expect ~£2,994 lower sales than average.",
    "Sunny":  "☀️ Sunny day — slight uplift expected.",
    "Cold":   "🥶 Cold weather — small boost expected (comfort food effect).",
    "Cloudy": "Typical trading conditions expected.",
}


# Stock item config — sales ratio converts forecast sales to units needed

STOCK_ITEMS = {
    "Lager (kegs)"        : {"unit_cost": 80,  "sales_ratio": 0.0035, "reorder_point": 3,   "max_stock": 20},
    "Ale (kegs)"          : {"unit_cost": 75,  "sales_ratio": 0.0020, "reorder_point": 2,   "max_stock": 15},
    "Wine (cases)"        : {"unit_cost": 120, "sales_ratio": 0.0015, "reorder_point": 5,   "max_stock": 30},
    "Spirits (bottles)"   : {"unit_cost": 25,  "sales_ratio": 0.0025, "reorder_point": 10,  "max_stock": 60},
    "Soft Drinks (cases)" : {"unit_cost": 18,  "sales_ratio": 0.0010, "reorder_point": 8,   "max_stock": 40},
    "Food Ingredients (£)": {"unit_cost": 1,   "sales_ratio": 0.3000, "reorder_point": 200, "max_stock": 800},
}

def estimate_stock_needed(forecast_sales, item):
    return max(1, round(forecast_sales * STOCK_ITEMS[item]["sales_ratio"]))

def stock_status(needed, cfg):
    if needed >= cfg["reorder_point"] * 1.5:
        return "HIGH",   "alert-high", "Order urgently"
    elif needed >= cfg["reorder_point"]:
        return "MEDIUM", "alert-med",  "Order soon"
    else:
        return "LOW",    "alert-ok",   "Stock sufficient"

def chart_layout(fig, height=350):
    fig.update_layout(
        height=height, margin=dict(t=20, b=40),
        plot_bgcolor=PLOT_BG, paper_bgcolor=PLOT_BG,
        font=dict(color=TEXT_MAIN),
        xaxis=dict(showgrid=True, gridcolor=GRID_CLR, color=TEXT_MAIN),
        yaxis=dict(showgrid=True, gridcolor=GRID_CLR, color=TEXT_MAIN),
        legend=dict(orientation="h", y=1.08, font=dict(color=TEXT_MAIN))
    )
    return fig

def get_weather_for_date(target_date, forecast_df):
    ts = pd.Timestamp(target_date)
    row = forecast_df[forecast_df["date"] == ts]

    if row.empty:
        return "Cloudy"

    r = row.iloc[0]

    if "weather" in r.index and pd.notna(r["weather"]):
        return str(r["weather"])
    if int(r.get("is_rainy", 0)) == 1:
        return "Rainy"
    if int(r.get("is_sunny", 0)) == 1:
        return "Sunny"
    if int(r.get("is_cold", 0)) == 1:
        return "Cold"

    return "Cloudy"

def get_reservations(target_date, hist_df, forecast_df):
    ts = pd.Timestamp(target_date)
    if ts.year == 2025:  # use actual historical reservations
        row = hist_df[hist_df["date"] == ts]
        if not row.empty:
            return int(row.iloc[0]["reservations"])
    row = forecast_df[forecast_df["date"] == ts]  # estimate from forecast sales
    if not row.empty:
        return max(10, min(220, int(row.iloc[0]["forecast_sales_gbp"] / 45)))
    return 0

def metric_card(col, value, label):
    col.markdown(
        f'<div class="metric-card">'
        f'<div class="metric-value">{value}</div>'
        f'<div class="metric-label">{label}</div>'
        f'</div>', unsafe_allow_html=True)


# Sidebar

# pull top 3 models by MAPE dynamically — updates when pub switches
top3   = metrics_df.sort_values("MAPE (%)").head(3).reset_index(drop=True)
medals = ["🥇", "🥈", "🥉"]

# production model is always SARIMAX — selected for interpretability not raw metric rank
sarimax_row = metrics_df[metrics_df["Model"].str.startswith("SARIMAX")]
sarimax_mape = f"{sarimax_row['MAPE (%)'].values[0]:.2f}%" if not sarimax_row.empty else "—"

st.sidebar.title("🍺 Pub Forecast")
st.sidebar.markdown("---")
st.sidebar.markdown(f"**Active pub:** {active_pub['label']}")
st.sidebar.markdown(f"**Peak days:** {active_pub['peak_days']}")
st.sidebar.markdown(f"**Peak season:** {active_pub['peak_season']}")
st.sidebar.markdown("---")
st.sidebar.markdown(f"**Historical data:** {len(hist_df)} days")
st.sidebar.markdown(f"**Forecast period:** 2026 (365 days)")
st.sidebar.markdown("---")
st.sidebar.markdown("**Top 3 models by MAPE**")
for i, row in top3.iterrows():
    st.sidebar.markdown(f"{medals[i]} {row['Model']} — MAPE {row['MAPE (%)']:.2f}%")
st.sidebar.markdown("---")
st.sidebar.markdown(f"**Production model:** SARIMAX")
st.sidebar.markdown(f"_MAPE {sarimax_mape} — selected for interpretability_")


# Top-level tabs

tab_dash, tab_inv, tab_rep, tab_set = st.tabs([
    "🏠  Dashboard",
    "📦  Inventory Management",
    "📊  Reports & Data",
    "⚙️  Settings"
])


# Tab 1 — Dashboard

with tab_dash:
    st.title("Demand Forecast Dashboard")
    st.markdown("Today's snapshot and 2025 vs 2026 sales overview.")
    st.divider()

    # resolve view date — default today, clamped to 2026 forecast range
    today_ts = pd.Timestamp.today().normalize()
    min_fc   = forecast_df["date"].min()
    max_fc   = forecast_df["date"].max()

    default_view = today_ts if min_fc <= today_ts <= max_fc else min_fc

    with st.expander("📅  View a different date", expanded=False):
        selected_date = st.date_input(
            "Select a date",
            value=default_view.date(),
            min_value=date(2026, 1, 1),
            max_value=date(2026, 12, 31),
            key="dash_date_picker"
        )
        view_ts = pd.Timestamp(selected_date)

    if "dash_date_picker" not in st.session_state:
        view_ts = default_view

    view_ts = max(min_fc, min(max_fc, view_ts))  # clamp to valid range

    is_today   = (view_ts.date() == pd.Timestamp.today().date())
    date_label = "Today" if is_today else view_ts.strftime("%A %d %B %Y")

    # get data for selected date
    weather_today = get_weather_for_date(view_ts, forecast_df)
    icon          = WEATHER_ICON.get(weather_today, "🌤️")
    gradient      = WEATHER_GRADIENT.get(weather_today, WEATHER_GRADIENT["Cloudy"])
    fc_row        = forecast_df[forecast_df["date"] == view_ts]
    fc_sales      = fc_row["forecast_sales_gbp"].values[0] if not fc_row.empty else 0
    reservations  = get_reservations(view_ts, hist_df, forecast_df)
    weekday_str   = view_ts.strftime("%A")

    # weather card and metric cards
    col_w, col_m = st.columns([1, 3])

    with col_w:
        st.markdown(f"""
        <div style="background:{gradient}; border-radius:14px; padding:28px 16px;
                    color:#fff; text-align:center; height:100%;">
            <div style="font-size:52px;">{icon}</div>
            <div style="font-size:20px; font-weight:700; margin-top:8px;">{weather_today}</div>
            <div style="font-size:13px; opacity:0.85; margin-top:4px;">{date_label}</div>
            <div style="font-size:11px; opacity:0.70; margin-top:10px; line-height:1.5;">
                Simulated from<br>Neutral weather scenario
            </div>
        </div>
        """, unsafe_allow_html=True)

    with col_m:
        c1, c2, c3 = st.columns(3)
        metric_card(c1, f"£{fc_sales:,.0f}", f"Forecast Sales — {date_label}")
        metric_card(c2, f"{reservations}",   f"Est. Reservations — {date_label}")
        metric_card(c3, weekday_str,          "Day of Week")
        st.markdown("<br>", unsafe_allow_html=True)
        wn = WEATHER_NOTES.get(weather_today, "")
        if wn:
            st.info(wn)

    st.markdown("<br>", unsafe_allow_html=True)

    # Period overview metrics
    st.subheader("Period Overview")
    next_7   = forecast_df[forecast_df["date"] >= today_ts].head(7)
    next_30  = forecast_df[forecast_df["date"] >= today_ts].head(30)
    avg_2025 = hist_df["sales_gbp"].mean()
    avg_2026 = forecast_df["forecast_sales_gbp"].mean()
    pct      = ((avg_2026 - avg_2025) / avg_2025) * 100
    arrow    = "↑" if pct > 0 else "↓"

    c1, c2, c3, c4 = st.columns(4)
    metric_card(c1, f"£{next_7['forecast_sales_gbp'].sum():,.0f}",  "Forecast — Next 7 Days")
    metric_card(c2, f"£{next_30['forecast_sales_gbp'].sum():,.0f}", "Forecast — Next 30 Days")
    metric_card(c3, f"£{avg_2026:,.0f}",                            "Avg Daily Forecast (2026)")
    metric_card(c4, f"{arrow} {abs(pct):.1f}%",                     "Forecast vs 2025 Average")

    st.markdown("<br>", unsafe_allow_html=True)

    # Historical vs forecast chart
    st.subheader("Historical Sales (2025) vs Forecast (2026)")
    view = st.radio("View", ["Daily", "Weekly average", "Monthly average"], horizontal=True)

    rule_map = {"Weekly average": "W", "Monthly average": "ME"}
    if view in rule_map:
        hp = hist_df.set_index("date")["sales_gbp"].resample(rule_map[view]).mean().reset_index()
        fp = forecast_df.set_index("date")["forecast_sales_gbp"].resample(rule_map[view]).mean().reset_index()
    else:
        hp = hist_df[["date","sales_gbp"]]
        fp = forecast_df[["date","forecast_sales_gbp"]]

    fig = go.Figure()
    fig.add_trace(go.Scatter(x=hp["date"], y=hp["sales_gbp"],
                             name="Actual 2025", line=dict(color="#3b82f6", width=1.8)))
    fig.add_trace(go.Scatter(x=fp["date"], y=fp["forecast_sales_gbp"],
                             name="Forecast 2026", line=dict(color="#ef4444", width=1.8, dash="dot")))
    st.plotly_chart(chart_layout(fig, 380), use_container_width=True)

    # Day of week pattern — peak days differ per pub
    st.subheader("2026 Weekly Pattern — Average Sales by Day of Week")
    forecast_df["weekday"] = pd.to_datetime(forecast_df["date"]).dt.day_name()
    day_order    = ["Monday","Tuesday","Wednesday","Thursday","Friday","Saturday","Sunday"]
    day_avg      = forecast_df.groupby("weekday")["forecast_sales_gbp"].mean().reindex(day_order).reset_index()
    peak_days    = active_pub["peak_days"]

    # colour top 2 days red for riverside (Thu+Fri), top 1 red for local (Thu)
    sorted_days  = day_avg.sort_values("forecast_sales_gbp", ascending=False)["weekday"].tolist()
    top_days     = sorted_days[:2] if pub_key == "riverside" else sorted_days[:1]
    bar_colours  = ["#ef4444" if d in top_days else "#3b82f6" if d == sorted_days[2] else "#94a3b8"
                    for d in day_order]

    fig_day = go.Figure()
    fig_day.add_trace(go.Bar(
        x=day_avg["weekday"], y=day_avg["forecast_sales_gbp"],
        marker_color=bar_colours
    ))
    fig_day.update_layout(xaxis_title="Day", yaxis_title="Avg Forecast Sales (£)", showlegend=False)
    st.plotly_chart(chart_layout(fig_day, 320), use_container_width=True)
    st.caption(f"Peak days: {peak_days} (red). Plan stock orders accordingly.")

    # Model performance summary table
    st.subheader("Model Performance Summary")
    st.dataframe(
        metrics_df.style
        .highlight_min(subset=["MAPE (%)"], color="#bbf7d0")
        .highlight_min(subset=["RMSE (£)"],  color="#bbf7d0")
        .format({"MAPE (%)": "{:.2f}%", "RMSE (£)": "£{:,.0f}"}),
        use_container_width=True)
    st.caption(f"Green = best value per metric. {top3.iloc[0]['Model']} wins on MAPE ({top3.iloc[0]['MAPE (%)']:.2f}%). SARIMAX (MAPE {sarimax_mape}) is selected as production model for its interpretable weather coefficients.")

    # Random forest feature importance chart
    st.subheader("Random Forest — Feature Importance")
    fi_display = fi_df.copy()
    fi_display["Importance %"] = (fi_display["Importance"] * 100).round(2)
    fig_fi = go.Figure()
    fig_fi.add_trace(go.Bar(
        x=fi_display["Importance %"], y=fi_display["Feature"], orientation="h",
        marker_color=["#ef4444" if i < 2 else "#3b82f6" if i < 4 else "#94a3b8"
                      for i in range(len(fi_display))],
        text=fi_display["Importance %"].apply(lambda x: f"{x:.1f}%"),
        textposition="outside"
    ))
    fig_fi.update_layout(xaxis_title="Importance (%)", yaxis_title="",
                         showlegend=False, yaxis=dict(autorange="reversed"))
    st.plotly_chart(chart_layout(fig_fi, 400), use_container_width=True)
    st.caption("lag_14 and lag_7 dominate — past sales are the strongest predictor.")

    # Decision tree key rules
    st.subheader("Decision Tree — Key Rules")
    col1, col2, col3 = st.columns(3)
    for col, title, body in [
        (col1, "lag_14 ≤ £7,651",
         "Root split — if sales 2 weeks ago were low, predict low. Tree independently discovered weekly seasonality."),
        (col2, "is_rainy = 1",
         "Rain is the most important weather split — rainy Sunday predicts only £1,211 vs £6,409 for a dry mid-week day."),
        (col3, "day_of_week > 5.5",
         "Sunday (6) is split out explicitly — confirming it is the lowest sales day even in the ML model."),
    ]:
        col.markdown(f"""<div class="metric-card">
            <div class="metric-value" style="font-size:18px;">{title}</div>
            <div class="metric-label">{body}</div>
        </div>""", unsafe_allow_html=True)


# Tab 2 — Inventory Management

with tab_inv:
    st.title("Inventory Management")
    st.markdown("Stock level recommendations based on 2026 demand forecasts.")
    st.divider()

    c1, c2 = st.columns(2)
    with c1:
        start_date = st.date_input("From date", value=date(2026,1,1),
                                   min_value=date(2026,1,1), max_value=date(2026,12,31),
                                   key="inv_start")
    with c2:
        end_date = st.date_input("To date", value=date(2026,1,7),
                                 min_value=date(2026,1,1), max_value=date(2026,12,31),
                                 key="inv_end")

    if start_date > end_date:
        st.warning("End date must be after start date.")
        st.stop()

    mask      = (forecast_df["date"].dt.date >= start_date) & (forecast_df["date"].dt.date <= end_date)
    period_df = forecast_df[mask].copy()

    if period_df.empty:
        st.warning("No forecast data for selected dates.")
        st.stop()

    total_forecast = period_df["forecast_sales_gbp"].sum()
    avg_daily      = period_df["forecast_sales_gbp"].mean()
    n_days         = len(period_df)

    c1, c2, c3 = st.columns(3)
    metric_card(c1, f"£{total_forecast:,.0f}", "Total Forecast Sales")
    metric_card(c2, f"£{avg_daily:,.0f}",      "Average Daily Sales")
    metric_card(c3, str(n_days),               "Days Selected")

    st.markdown("<br>", unsafe_allow_html=True)

    # Daily forecast bar chart for selected period
    st.subheader("Daily Forecast for Selected Period")
    period_df["weekday_label"] = pd.to_datetime(period_df["date"]).dt.strftime("%a %d %b")
    fig3 = go.Figure()
    fig3.add_trace(go.Bar(
        x=period_df["weekday_label"],
        y=period_df["forecast_sales_gbp"],
        marker_color="#3b82f6",
        text=period_df["forecast_sales_gbp"].apply(lambda x: f"£{x:,.0f}"),
        textposition="outside"
    ))
    fig3.update_layout(xaxis_title="Date", yaxis_title="Forecast Sales (£)", showlegend=False)
    st.plotly_chart(chart_layout(fig3, 320), use_container_width=True)

    # Stock recommendations based on total forecast sales
    st.subheader("Stock Order Recommendations")
    st.caption(f"Based on total forecast sales of £{total_forecast:,.0f} over {n_days} days.")

    rows = []
    for item, cfg in STOCK_ITEMS.items():
        needed     = estimate_stock_needed(total_forecast, item)
        unit       = "units" if item != "Food Ingredients (£)" else "£"
        status, css_class, advice = stock_status(needed, cfg)
        total_cost = needed * cfg["unit_cost"] if item != "Food Ingredients (£)" else needed
        st.markdown(
            f'<div class="{css_class}"><strong>{item}</strong> — '
            f'Order <strong>{needed} {unit}</strong> &nbsp;·&nbsp; {advice}</div>',
            unsafe_allow_html=True)
        rows.append({"Item": item, "Units Needed": f"{needed} {unit}",
                     "Reorder Point": cfg["reorder_point"], "Status": status,
                     "Advice": advice, "Est. Order Cost": f"£{total_cost:,.0f}"})

    st.markdown("<br>", unsafe_allow_html=True)
    st.subheader("Stock Order Summary Table")
    st.dataframe(pd.DataFrame(rows), use_container_width=True, hide_index=True)
    st.info("💡 Thursday and Friday are peak demand days across 2026. Place stock orders mid-week to avoid shortages on your busiest days.")


# Tab 3 — Reports and Data

with tab_rep:
    st.title("Reports & Data")
    st.markdown("Download forecasts and review model performance.")
    st.divider()

    r_tab1, r_tab2 = st.tabs(["📅  2026 Demand Forecast", "🤖  Model Performance"])

    with r_tab1:
        st.subheader("2026 Demand Forecast")
        month_filter = st.selectbox("Filter by month",
                                    ["All","January","February","March","April","May","June",
                                     "July","August","September","October","November","December"])

        display_df = forecast_df[["date","weekday","forecast_sales_gbp"]].copy()
        display_df.columns = ["Date","Day","Forecast Sales (£)"]
        display_df["Forecast Sales (£)"] = display_df["Forecast Sales (£)"].round(2)

        if month_filter != "All":
            m = ["January","February","March","April","May","June","July",
                 "August","September","October","November","December"].index(month_filter) + 1
            display_df = display_df[display_df["Date"].dt.month == m]

        st.dataframe(display_df, use_container_width=True, hide_index=True)
        buf = io.StringIO()
        display_df.to_csv(buf, index=False)
        st.download_button("⬇️ Download forecast as CSV", data=buf.getvalue(),
                           file_name="forecast_2026.csv", mime="text/csv")

    with r_tab2:
        st.subheader("Model Performance Comparison")
        st.dataframe(
            metrics_df.style
            .highlight_min(subset=["MAPE (%)"], color="#bbf7d0")
            .highlight_min(subset=["RMSE (£)"],  color="#bbf7d0")
            .format({"MAPE (%)": "{:.2f}%", "RMSE (£)": "£{:,.0f}"}),
            use_container_width=True)

        st.markdown("**How to read this table:**")
        st.markdown("- **MAPE** — Mean Absolute Percentage Error. Lower is better.")
        st.markdown("- **RMSE** — Root Mean Square Error (£). Lower is better. More sensitive to large errors, which matters most for inventory planning.")
        st.markdown("**Model selection rationale:**")
        rf_row  = metrics_df[metrics_df["Model"].str.startswith("Random Forest")]
        lr_row  = metrics_df[metrics_df["Model"].str.startswith("Linear Regression")]
        ma_row  = metrics_df[metrics_df["Model"].str.startswith("Moving Average")]
        rf_mape = f"{rf_row['MAPE (%)'].values[0]:.2f}%" if not rf_row.empty else "—"
        lr_rmse = f"£{lr_row['RMSE (£)'].values[0]:,.0f}" if not lr_row.empty else "—"
        ma_mape = f"{ma_row['MAPE (%)'].values[0]:.0f}%" if not ma_row.empty else "—"
        st.markdown(f"- **Random Forest** achieves the best MAPE ({rf_mape}) but is a black box — it cannot explain *why* it predicts a certain value.")
        st.markdown(f"- **SARIMAX** (MAPE {sarimax_mape}) provides statistically interpretable weather coefficients — e.g. rain reduces daily sales by approximately £2,980. Selected as production model for its interpretability.")
        st.markdown(f"- **Linear Regression** achieves best RMSE ({lr_rmse}) — competitive on smooth, regular demand patterns.")
        st.markdown("- **Decision Tree** is interpretable but less accurate than ensemble methods.")
        st.markdown(f"- **Moving Average** is the naive baseline — its {ma_mape} MAPE shows the value added by all other models.")

        # MAPE chart
        st.subheader("MAPE Comparison Chart")
        fig6 = px.bar(metrics_df.sort_values("MAPE (%)"),
                      x="MAPE (%)", y="Model", orientation="h",
                      color="MAPE (%)", color_continuous_scale=["#22c55e","#f59e0b","#ef4444"])
        fig6.update_layout(coloraxis_showscale=False)
        st.plotly_chart(chart_layout(fig6, 380), use_container_width=True)

        # RMSE chart
        st.subheader("RMSE Comparison Chart")
        fig7 = px.bar(metrics_df.sort_values("RMSE (£)"),
                      x="RMSE (£)", y="Model", orientation="h",
                      color="RMSE (£)", color_continuous_scale=["#22c55e","#f59e0b","#ef4444"])
        fig7.update_layout(coloraxis_showscale=False)
        st.plotly_chart(chart_layout(fig7, 380), use_container_width=True)

        # Feature importance chart
        st.subheader("Random Forest — Feature Importance")
        fi_display2 = fi_df.copy()
        fi_display2["Importance %"] = (fi_display2["Importance"] * 100).round(2)
        fig_fi2 = go.Figure()
        fig_fi2.add_trace(go.Bar(
            x=fi_display2["Importance %"], y=fi_display2["Feature"], orientation="h",
            marker_color=["#ef4444" if i < 2 else "#3b82f6" if i < 4 else "#94a3b8"
                          for i in range(len(fi_display2))],
            text=fi_display2["Importance %"].apply(lambda x: f"{x:.1f}%"),
            textposition="outside"
        ))
        fig_fi2.update_layout(xaxis_title="Importance (%)", showlegend=False,
                              yaxis=dict(autorange="reversed"))
        st.plotly_chart(chart_layout(fig_fi2, 400), use_container_width=True)
        st.caption("lag_14 (63.97%) and lag_7 (28.63%) account for 92% of predictive power.")


# Tab 4 — Settings

with tab_set:
    st.title("Settings")
    st.divider()

    # Pub selector — switches all data, forecasts and charts across the whole app
    st.subheader("🏪  Select Pub")
    st.markdown("Switch the active pub to compare forecasts between the two datasets.")

    pub_labels   = [v["label"] for v in PUB_OPTIONS.values()]
    pub_keys     = list(PUB_OPTIONS.keys())
    current_idx  = pub_keys.index(st.session_state.selected_pub)

    col_p1, col_p2 = st.columns(2)
    with col_p1:
        st.markdown(f"""<div class="metric-card">
            <div class="metric-value" style="font-size:18px;">🏠 Local Pub</div>
            <div class="metric-label">Peak: Thursday & Friday<br>Season: Christmas (December)<br>Database: pub_sales.db</div>
        </div>""", unsafe_allow_html=True)
    with col_p2:
        st.markdown(f"""<div class="metric-card">
            <div class="metric-value" style="font-size:18px;">🌊 Riverside Pub (London)</div>
            <div class="metric-label">Peak: Thursday – Sunday<br>Season: Summer (June – August)<br>Database: riverside_pub_sales.db</div>
        </div>""", unsafe_allow_html=True)

    st.markdown("<br>", unsafe_allow_html=True)

    pub_choice = st.radio(
        "Active pub",
        options=pub_labels,
        index=current_idx,
        horizontal=True
    )

    chosen_key = pub_keys[pub_labels.index(pub_choice)]

    if chosen_key != st.session_state.selected_pub:
        st.session_state.selected_pub = chosen_key
        st.rerun()  # reload all data for the newly selected pub

    st.success(f"Currently showing: **{active_pub['label']}**")
    st.caption("All pages — Dashboard, Inventory, Reports — update automatically when you switch pub.")

    st.divider()

    # Theme toggle
    st.subheader("🎨  Theme")
    theme_choice = st.radio(
        "Select display theme",
        ["Light", "Dark"],
        index=1 if st.session_state.dark_mode else 0,
        horizontal=True
    )
    if (theme_choice == "Dark") != st.session_state.dark_mode:
        st.session_state.dark_mode = (theme_choice == "Dark")
        st.rerun()  # rerun so theme applies immediately
    st.caption("Theme applies across all pages immediately.")

    st.divider()

    # PDF report generator
    st.subheader("🖨️  Print Report")
    st.markdown("Generate a PDF summary of the 2026 forecast and stock order recommendations.")

    col_r1, col_r2 = st.columns(2)
    with col_r1:
        report_start = st.date_input("Report from", value=date(2026,1,1),
                                     min_value=date(2026,1,1), max_value=date(2026,12,31),
                                     key="rep_start")
    with col_r2:
        report_end = st.date_input("Report to", value=date(2026,1,31),
                                   min_value=date(2026,1,1), max_value=date(2026,12,31),
                                   key="rep_end")

    if st.button("📄 Generate PDF Report"):
        try:
            from reportlab.lib.pagesizes import A4
            from reportlab.lib import colors
            from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
            from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
            from reportlab.lib.units import cm

            mask_r  = ((forecast_df["date"].dt.date >= report_start) &
                       (forecast_df["date"].dt.date <= report_end))
            rep_df  = forecast_df[mask_r].copy()
            total_r = rep_df["forecast_sales_gbp"].sum()
            avg_r   = rep_df["forecast_sales_gbp"].mean()
            n_r     = len(rep_df)

            buf_pdf = io.BytesIO()
            doc     = SimpleDocTemplate(buf_pdf, pagesize=A4,
                                        rightMargin=2*cm, leftMargin=2*cm,
                                        topMargin=2*cm, bottomMargin=2*cm)
            styles       = getSampleStyleSheet()
            title_style  = ParagraphStyle("title", parent=styles["Heading1"], fontSize=18, spaceAfter=6)
            h2_style     = ParagraphStyle("h2", parent=styles["Heading2"], fontSize=13, spaceBefore=14, spaceAfter=4)
            body_style   = styles["Normal"]
            footer_style = ParagraphStyle("footer", parent=body_style, fontSize=8,
                                          textColor=colors.HexColor("#6b7280"))

            HDR = colors.HexColor("#1d4ed8")
            ROW = [colors.HexColor("#f9fafb"), colors.white]
            GRD = colors.HexColor("#e5e7eb")

            def table_style(col_widths):
                return TableStyle([
                    ("BACKGROUND",     (0,0), (-1,0), HDR),
                    ("TEXTCOLOR",      (0,0), (-1,0), colors.white),
                    ("FONTNAME",       (0,0), (-1,0), "Helvetica-Bold"),
                    ("FONTSIZE",       (0,0), (-1,-1), 9),
                    ("ROWBACKGROUNDS", (0,1), (-1,-1), ROW),
                    ("GRID",           (0,0), (-1,-1), 0.5, GRD),
                    ("TOPPADDING",     (0,0), (-1,-1), 5),
                    ("BOTTOMPADDING",  (0,0), (-1,-1), 5),
                    ("LEFTPADDING",    (0,0), (-1,-1), 7),
                ])

            story = []

            story.append(Paragraph("🍺 Pub Forecast — Demand & Stock Report", title_style))
            story.append(Paragraph(
                f"Period: {report_start.strftime('%d %b %Y')} to {report_end.strftime('%d %b %Y')}  "
                f"|  Generated: {datetime.today().strftime('%d %b %Y %H:%M')}",
                body_style))
            story.append(Spacer(1, 0.5*cm))

            # forecast summary table
            story.append(Paragraph("Forecast Summary", h2_style))
            summary_data = [
                ["Metric", "Value"],
                ["Total Forecast Sales",     f"£{total_r:,.0f}"],
                ["Average Daily Sales",      f"£{avg_r:,.0f}"],
                ["Days in Period",           str(n_r)],
                ["Production Model",         production_row["Model"]],
                ["Production Model MAPE",    f"{production_row['MAPE (%)']:.2f}%"],
                ["Production Model RMSE",    f"£{production_row['RMSE (£)']:,.0f}"],
            ]
            t1 = Table(summary_data, colWidths=[9*cm, 7*cm])
            t1.setStyle(table_style([9*cm, 7*cm]))
            story.append(t1)
            story.append(Spacer(1, 0.4*cm))

            # stock recommendations table
            story.append(Paragraph("Stock Order Recommendations", h2_style))
            stock_data = [["Item", "Units Needed", "Status", "Est. Cost"]]
            for item, cfg in STOCK_ITEMS.items():
                needed     = estimate_stock_needed(total_r, item)
                unit       = "units" if item != "Food Ingredients (£)" else "£"
                status, _, advice = stock_status(needed, cfg)
                total_cost = needed * cfg["unit_cost"] if item != "Food Ingredients (£)" else needed
                stock_data.append([item, f"{needed} {unit}", f"{status} — {advice}", f"£{total_cost:,.0f}"])
            t2 = Table(stock_data, colWidths=[6*cm, 3.5*cm, 4.5*cm, 3*cm])
            t2.setStyle(table_style([6*cm, 3.5*cm, 4.5*cm, 3*cm]))
            story.append(t2)
            story.append(Spacer(1, 0.4*cm))

            # daily breakdown table
            story.append(Paragraph("Daily Forecast Breakdown", h2_style))
            daily_data = [["Date", "Day", "Forecast Sales (£)"]]
            for _, row in rep_df.iterrows():
                daily_data.append([
                    row["date"].strftime("%d %b %Y"),
                    row["weekday"],
                    f"£{row['forecast_sales_gbp']:,.0f}"
                ])
            t3 = Table(daily_data, colWidths=[5*cm, 4*cm, 8*cm])
            t3.setStyle(table_style([5*cm, 4*cm, 8*cm]))
            story.append(t3)
            story.append(Spacer(1, 0.6*cm))
            story.append(Paragraph(
                "Generated by Pub Forecast System | Smart Inventory Management with Demand Forecasting | BSc Computer Science FYP",
                footer_style))

            doc.build(story)
            buf_pdf.seek(0)

            st.success("✅ Report generated successfully!")
            st.download_button(
                label="⬇️ Download PDF Report",
                data=buf_pdf,
                file_name=f"pub_forecast_{report_start}_to_{report_end}.pdf",
                mime="application/pdf"
            )

        except ImportError:
            st.error("reportlab is not installed. Run:  pip install reportlab")
        except Exception as e:
            st.error(f"PDF generation failed: {e}")

    st.divider()

    # About section
    st.subheader("ℹ️  About")
    st.markdown(f"""
| Detail | Value |
|---|---|
| Dataset | Synthetic pub sales, 2025 (365 days) |
| Production model | {production_row['Model']} |
| Models compared | {len(metrics_df)} |
| Best MAPE | {best_mape_row['Model']} — {best_mape_row['MAPE (%)']:.2f}% |
| Best RMSE | {best_rmse_row['Model']} — £{best_rmse_row['RMSE (£)']:,.0f} |
| Forecast period | 2026 (Neutral weather scenario) |
| Framework | Python · Streamlit · statsmodels · scikit-learn · Plotly |
""")
    st.caption("BSc Computer Science — Finsal Year Project")